auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: allen2660.github.io
url: http://allen2660.github.io
feed: /atom.xml
author_info: <a href="http://allen2660.github.io">allen2660</a>
